FROM ubuntu:22.04
RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get install -y openssh-client
RUN mkdir /var/run/sshd && \
    chmod 0755 /var/run/sshd
RUN echo "root:8675309" | chpasswd
RUN echo "Welcome to the isolated host environment." > message.txt
COPY private-key .
RUN chmod 600 private-key
CMD ["sh", "-c", "/usr/sbin/sshd && ssh -N -T -R *:2222:localhost:22 -o StrictHostKeyChecking=no -i ./private-key provider00001@54.175.222.240 -p 22"]

